[tool.poetry]
name = "news-assistent"
version = "0.1.0"
description = ""
authors = ["Ievgenii Zhmur <i.am.zhmur@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
